# ================================================================================
# FamilyLife-style story event runtime split.
# Engine code lives in conditions.rpy, threads.rpy, and events.rpy.
# Authored thread definitions and event labels stay in StoryEventRuntime.rpy for now.
# ================================================================================

define amandaThreadList = []

define melissaThreadList = [
    #
    # melissa_rat_problem
    #
    # Event tuple columns:
    # (target, day, hour, delay, probability, reqs, condition, item, location, action, priority)
    #
    LThreadData(0, "melissa", "RatProblem", None, [
        (
            "story_melissa_storage_rat_0",
            (1, 6), (6, 7), None,
            1,
            None,
            [
                "#int(Melissa.var.get('storage_rat_cleared', 0) or 0) == 0",
                "#str(getLocation('melissa') or '') == 'TavernStorage'",
                "#not household_runtime_event_seen_today('melissa_storage_rat')",
            ],
            None,
            "TavernStorage",
            "enter",
            0,
        ),
    ], highlight=False, threaded=True),
    #
    # melissa_werecat_problem
    #
    LThreadData(0, "melissa", "WerecatProblem", "melissaRatProblem_0", [
        (
            "story_melissa_werecat_rumor_0",
            None, None, None,
            1,
            None,
            [
                "#not (int(WerecatVar.get('sold', 0) or 0) == 0 and int(WerecatVar.get('adopted_count', 0) or 0) >= 1)",
                "#int(WerecatVar.get('rats_problem_active', 0) or 0) == 1",
                "#int(Melissa.var.get('storage_rat_cleared', 0) or 0) == 1",
                "#int(Melissa.var.get('storage_rat_last_help_day', -1) or -1) >= 0",
                "#int(WerecatVar.get('adopted', 0) or 0) == 0",
                "#int(WerecatVar.get('sold', 0) or 0) == 0",
                "#int(WerecatVar.get('hunter_tease_day', -1) or -1) < 0",
            ],
            None,
            "HunterClub",
            "overheard",
            0,
        ),
        (
            "story_melissa_werecat_intro_0",
            (1, 7), (6, 7), None,
            1,
            None,
            [
                "#int(WerecatVar.get('rats_problem_active', 0) or 0) == 1",
                "#int(WerecatVar.get('rat_breakfast_seen', 0) or 0) == 0",
                "#int(WerecatVar.get('hunter_tease_day', -1) or -1) >= 0",
                "#not bool(BreakfastToday)",
            ],
            None,
            "TavernKitchen",
            "enter",
            1,
        ),
        (
            "story_melissa_werecat_home_0",
            (1, 7), (6, 7), None,
            1,
            None,
            [
                "#int(WerecatVar.get('adopted', 0) or 0) == 1",
                "#int(WerecatVar.get('adoption_breakfast_seen', 0) or 0) == 0",
                "#int(WerecatVar.get('adopted_day', -1) or -1) >= 0",
                "#day_delta_ready(WerecatVar.get('adopted_day', -1), 1)",
                "#not bool(BreakfastToday)",
            ],
            None,
            "TavernKitchen",
            "enter",
            2,
        ),
        (
            "story_melissa_werecat_home_1",
            (1, 7), (6, 7), None,
            1,
            None,
            [
                "#int(WerecatVar.get('adopted', 0) or 0) == 1",
                "#int(WerecatVar.get('adoption_breakfast_seen', 0) or 0) == 1",
                "#int(WerecatVar.get('adopted_day', -1) or -1) >= 0",
                "#day_delta_ready(WerecatVar.get('adopted_day', -1), 30)",
                "#int(WerecatVar.get('first_month_thanks_day', -1) or -1) < int(WerecatVar.get('adopted_day', -1) or -1) + 30",
                "#not bool(BreakfastToday)",
            ],
            None,
            "TavernKitchen",
            "enter",
            3,
        ),
    ], highlight=False, threaded=True),
    # bats_problem_thread
    # Rat cleanup in storage is the household trigger; this ordered bat problem
    # starts at the next available breakfast.
    LThreadData(0, "melissa", "BatProblem", "melissaRatProblem_0", [
        (
            "story_melissa_bat_problem_0",
            (1, 7), (6, 7), None,
            1,
            None,
            [
                "#int(Melissa.var.get('bats_episode', 0) or 0) <= 0",
                "#int(Melissa.var.get('storage_rat_last_help_day', -1) or -1) >= 0",
                "#not bool(BreakfastToday)",
            ],
            None,
            "TavernKitchen",
            "enter",
            0,
        ),
        (
            "story_melissa_bat_problem_1",
            None, (16, 17), None,
            1,
            None,
            [
                "#int(Melissa.var.get('bats_episode', 0) or 0) == 1",
            ],
            None,
            "TavernUpstairs",
            "enter",
            1,
        ),
        (
            "story_melissa_bat_problem_2",
            None, None, None,
            1,
            None,
            [
                "#int(Melissa.var.get('bats_episode', 0) or 0) == 3",
                "#int(dayspassed or 0) >= int(Melissa.var.get('bat_attic_check_day', -1) or -1)",
            ],
            None,
            "TavernAtic",
            "melissa_bats",
            2,
        ),
        (
            "story_melissa_bat_problem_3",
            None, None, None,
            1,
            None,
            [
                "#int(Melissa.var.get('bats_episode', 0) or 0) in (4, 5)",
            ],
            None,
            "TavernAtic",
            "melissa_bats",
            3,
        ),
        (
            "story_melissa_bat_problem_5",
            None, None, None,
            1,
            None,
            [
                "#int(Melissa.var.get('bats_episode', 0) or 0) >= 6",
                "#int(Melissa.var.get('bats_episode', 0) or 0) < 8",
                "#str(Melissa.var.get('temp_room', '') or '') == 'TavernAmandaRoom'",
                "#int(Melissa.var.get('drawings_found', 0) or 0) == 0",
                "#int(dayspassed or 0) >= int(Melissa.var.get('drawings_ready_day', -1) or -1)",
            ],
            None,
            "TavernMelissaRoom",
            "room_search",
            4,
        ),
        (
            "story_melissa_bat_problem_4",
            None, None, None,
            1,
            None,
            [
                "#int(Melissa.var.get('bats_episode', 0) or 0) >= 6",
                "#int(Melissa.var.get('bats_episode', 0) or 0) < 8",
            ],
            None,
            "TavernAtic",
            "melissa_bats",
            5,
        ),
        (
            "story_melissa_bat_problem_6",
            None, None, None,
            1,
            None,
            [
                "#int(Melissa.var.get('bats_episode', 0) or 0) == 7",
                "#int(Melissa.var.get('roof_repair_complete_day', -1) or -1) >= 0",
                "#int(dayspassed or 0) >= int(Melissa.var.get('roof_repair_complete_day', -1) or -1)",
                "#int(Melissa.var.get('drawings_returned', 0) or 0) == 1",
            ],
            None,
            "TavernMain",
            "melissa_talk",
            6,
        ),
    ], highlight=False, threaded=True),
]

define sandraThreadList = [
    LThreadData(0, "sandra", "WeeklyEvaluation", None, [
        ("sandraWeeklyEvaluation_0", None, None, None, 1, None, ["#Sandra.weekly_thanks_event_ready()"], None, "TavernMyRoom", "sleep", 0),
        ("sandraWeeklyEvaluation_1", None, None, None, 1, None, ["#Sandra.weekly_thanks_event_ready()"], None, "TavernMyRoom", "sleep", 1),
        ("sandraWeeklyEvaluation_2", None, None, None, 1, None, ["#Sandra.weekly_thanks_event_ready()"], None, "TavernMyRoom", "sleep", 2),
        ("sandraWeeklyEvaluation_3", None, None, None, 1, None, ["#Sandra.weekly_thanks_event_ready()"], None, "TavernMyRoom", "sleep", 3),
    ], highlight=False, threaded=True),
]
define claraThreadList = [
    LThreadData(0, "clara", "BookletMarket", None, [
        (
            "story_clara_market_booklet_0",
            [1, 2, 3, 4, 5, 6], (11, 12), None,
            1,
            None,
            [
                "#int(ClaraVar.get('market_day_roll_day', -1) or -1) == int(dayspassed or 0)",
                "#int(ClaraVar.get('market_day_roll', 0) or 0) == 1",
                "#int(ClaraVar.get('booklet_market_seen', 0) or 0) == 0",
                "#not (int(ClaraVar.get('market_follow_failed_day', -1) or -1) == int(dayspassed or 0) and int(ClaraVar.get('market_follow_failed_hour', -1) or -1) == int(hour or 0))",
            ],
            None,
            "MarketPlace",
            "enter",
            0,
        ),
        (
            "story_clara_market_booklet_2",
            [1, 2, 3, 4, 6], (13, 15), None,
            1,
            None,
            [
                "#int(ClaraVar.get('market_evening_roll_day', -1) or -1) == int(dayspassed or 0)",
                "#int(ClaraVar.get('market_evening_roll', 0) or 0) == 1",
                "#int(ClaraVar.get('booklet_market_seen', 0) or 0) == 1",
                "#int(ClaraVar.get('market_evening_intro_seen', 0) or 0) == 0",
            ],
            None,
            "MarketPlace",
            "enter",
            1,
        ),
        (
            "story_clara_market_booklet_3",
            [1, 2, 3, 4, 6], (13, 15), None,
            1,
            None,
            [
                "#int(ClaraVar.get('market_evening_roll_day', -1) or -1) == int(dayspassed or 0)",
                "#int(ClaraVar.get('market_evening_roll', 0) or 0) == 1",
                "#int(ClaraVar.get('market_evening_intro_seen', 0) or 0) == 1",
                "#int(ClaraVar.get('mongol_theft_seen', 0) or 0) == 0",
            ],
            None,
            "MarketPlace",
            "enter",
            2,
        ),
        (
            "story_clara_market_booklet_4",
            None, None, None,
            1,
            None,
            [
                "#int(ClaraVar.get('mongol_theft_seen', 0) or 0) == 1",
                "#int(ClaraVar.get('escape_confessed', 0) or 0) == 0",
            ],
            None,
            "WineStore",
            "clara_talk",
            3,
        ),
        (
            "story_clara_market_booklet_5",
            None, None, None,
            1,
            None,
            [
                "#int(ClaraVar.get('escape_confessed', 0) or 0) == 1",
                "#int(MongolVar.get('StocksArrestDay', -1) or -1) < 0",
            ],
            None,
            "HunterClub",
            "overheard",
            4,
        ),
        (
            "story_clara_market_booklet_6",
            None, None, None,
            1,
            None,
            [
                "#int(MongolVar.get('StocksArrestDay', -1) or -1) >= 0",
                "#int(MongolVar.get('StocksSeen', 0) or 0) == 0",
            ],
            None,
            "CityGuard",
            "enter",
            5,
        ),
        (
            "story_clara_market_booklet_7",
            None, (16, 17), None,
            1,
            None,
            [
                "#int(MongolVar.get('StocksSeen', 0) or 0) == 1",
                "#int(MongolVar.get('StocksFoodDay', -1) or -1) < 0",
            ],
            None,
            "CityGuard",
            "enter",
            6,
        ),
        (
            "story_clara_market_booklet_8",
            (1, 6), (6, 12), None,
            1,
            None,
            [
                "#int(MongolVar.get('StocksFoodDay', -1) or -1) >= 0",
                "#int(DraupnirVar.get('MongolLockpickOrderDay', -1) or -1) < 0",
            ],
            None,
            "StolyarWorkshop",
            "enter",
            7,
        ),
        (
            "story_clara_market_booklet_9",
            None, (16, 17), None,
            1,
            None,
            [
                "#int(DraupnirVar.get('MongolLockpickOrderDay', -1) or -1) >= 0",
                "#int(MongolVar.get('StocksReleased', 0) or 0) == 0",
                "#int(dayspassed or 0) > int(MongolVar.get('StocksFoodDay', -1) or -1)",
            ],
            None,
            "CityGuard",
            "enter",
            8,
        ),
    ], highlight=False, threaded=True),
    #
    # clara_paintings_path
    #
    # Event tuple columns:
    # (target, day, hour, delay, probability, reqs, condition, item, location, action, priority)
    #
    LThreadData(1, "clara", "PaintingsPath", None, [
        (
            "story_clara_paintings_melissa_0",
            None, None, None,
            1,
            None,
            [
                "#int(Melissa.var.get('drawings_found', 0) or 0) == 1",
                "#int(ClaraVar.get('paintings_melissa_asked', 0) or 0) == 0",
                "#int(AskedToday.get('melissa', 0) or 0) == 0",
            ],
            None,
            "talk_melissa",
            "clara_paintings",
            0,
        ),
        (
            "story_clara_paintings_cellar_1",
            None, (8, 12), None,
            1,
            None,
            [
                "#int(ClaraVar.get('paintings_melissa_asked', 0) or 0) == 1",
                "#int(ClaraVar.get('cellar_seen', 0) or 0) == 0",
                "#int(ClaraVar.get('flirt', 0) or 0) > 0",
            ],
            None,
            "WineStore",
            "clara_paintings",
            1,
        ),
        (
            "story_clara_paintings_comfort_2",
            None, (6, 7), None,
            1,
            None,
            [
                "#int(ClaraVar.get('comfort_pending', 0) or 0) == 1",
                "#int(ClaraVar.get('comfort_done', 0) or 0) == 0",
                "#str(getLocation('clara') or '') == 'WineStore'",
            ],
            None,
            "WineStore",
            "clara_paintings",
            2,
        ),
        (
            "story_clara_paintings_second_ask_3",
            None, None, None,
            1,
            None,
            [
                "#int(ClaraVar.get('second_ask_unlocked', 0) or 0) == 1",
                "#int(ClaraVar.get('source_known', 0) or 0) == 0",
            ],
            None,
            "WineStore",
            "clara_paintings",
            3,
        ),
        (
            "story_clara_paintings_church_4",
            7, (6, 12), None,
            1,
            None,
            [
                "#int(ClaraVar.get('source_known', 0) or 0) == 1",
                "#int(ClaraVar.get('fiance_church_seen', 0) or 0) == 0",
            ],
            None,
            "Church",
            "clara_paintings",
            4,
        ),
        (
            "story_clara_paintings_barber_5",
            None, None, None,
            1,
            None,
            [
                "#int(ClaraVar.get('fiance_church_seen', 0) or 0) == 1",
                "#int(ClaraVar.get('fiance_barber_seen', 0) or 0) == 0",
                "#(8 <= int(hour or 0) <= 10 or ((int(hour or 0) >= 23 or int(hour or 0) <= 5) and int(ClaraVar.get('fiance_barber_night_roll', 0) or 0) == 1))",
            ],
            None,
            "BarberShop",
            "clara_fiance",
            5,
        ),
        (
            "story_clara_paintings_commission_6",
            None, None, None,
            1,
            None,
            [
                "#int(ClaraVar.get('fiance_barber_seen', 0) or 0) == 1",
                "#int(ClaraVar.get('commission_started', 0) or 0) == 0",
                "#str(getLocation('clara') or '') == 'TavernMain'",
            ],
            None,
            "TavernMain",
            "clara_paintings",
            6,
        ),
        (
            "story_clara_paintings_commission_followup_7",
            None, (6, 7), None,
            1,
            None,
            [
                "#int(ClaraVar.get('commission_started', 0) or 0) == 1",
                "#int(ClaraVar.get('commission_followup_done', 0) or 0) == 0",
                "#int(dayspassed or 0) >= int(ClaraVar.get('commission_followup_day', 999999) or 999999)",
                "#str(getLocation('clara') or '') == 'WineStore'",
            ],
            None,
            "WineStore",
            "clara_paintings",
            7,
        ),
        (
            "story_clara_paintings_evening_peek_8",
            None, (13, 15), None,
            1,
            None,
            [
                "#int(ClaraVar.get('commission_followup_done', 0) or 0) == 1",
                "#int(ClaraVar.get('peek_done', 0) or 0) == 0",
                "#str(getLocation('clara') or '') == 'WineStore'",
            ],
            None,
            "WineStore",
            "clara_paintings",
            8,
        ),
        (
            "story_clara_paintings_confession_9",
            None, None, None,
            1,
            None,
            [
                "#int(ClaraVar.get('peek_done', 0) or 0) == 1",
                "#int(ClaraVar.get('confession_done', 0) or 0) == 0",
                "#str(getLocation('clara') or '') == 'TavernMelissaRoom'",
                "#str(getLocation('melissa') or '') == 'TavernMelissaRoom'",
            ],
            None,
            "TavernMelissaRoom",
            "clara_paintings",
            9,
        ),
        (
            "story_clara_paintings_murder_10",
            None, None, None,
            1,
            None,
            [
                "#int(ClaraVar.get('confession_done', 0) or 0) == 1",
                "#int(ClaraVar.get('murder_seen', 0) or 0) == 0",
                "#int(dayspassed or 0) >= int(ClaraVar.get('murder_day', 999999) or 999999)",
            ],
            None,
            "CityGuard",
            "enter",
            10,
        ),
    ], highlight=False, threaded=True),
    #
    # clara_tavern_visit
    #
    # Clara owns her visits with Melissa. Tavern rooms only expose the trigger
    # action; they do not register visits, choose pictures, or lock doors.
    LThreadData(2, "clara", "TavernVisit", None, [
        (
            "story_clara_tavern_visit_bar_0",
            [1, 2, 3, 4, 5, 6], (12, 17), None,
            1,
            None,
            [
                "#720 <= int(clock_minutes or 0) <= 1079",
                "#str(getLocation('clara') or '') == 'TavernMain'",
                "#str(getLocation('melissa') or '') == 'TavernMain'",
                "#int(Clara.var.get('tavern_visit_bar_0_seen', 0) or 0) == 0",
                "#not household_runtime_event_seen_today('clara_tavern_visit')",
            ],
            None,
            "TavernMain",
            "clara_tavern_visit",
            0,
        ),
        (
            "story_clara_tavern_visit_bar_1",
            [1, 2, 3, 4, 5, 6], (12, 17), None,
            1,
            None,
            [
                "#720 <= int(clock_minutes or 0) <= 1079",
                "#str(getLocation('clara') or '') == 'TavernMain'",
                "#str(getLocation('melissa') or '') == 'TavernMain'",
                "#int(Clara.var.get('tavern_visit_bar_0_seen', 0) or 0) == 1",
                "#int(Clara.var.get('tavern_visit_bar_1_seen', 0) or 0) == 0",
                "#int(AmandaVar.get('attic_window_busted', 0) or 0) == 1",
                "#int(Melissa.var.get('bats_episode', 0) or 0) >= 6",
                "#not household_runtime_event_seen_today('clara_tavern_visit')",
            ],
            None,
            "TavernMain",
            "clara_tavern_visit",
            1,
        ),
        (
            "story_clara_tavern_visit_bar_2",
            [1, 2, 3, 4, 5, 6], (18, 22), None,
            1,
            None,
            [
                "#1080 <= int(clock_minutes or 0) <= 1379",
                "#str(getLocation('clara') or '') == 'TavernMain'",
                "#str(getLocation('melissa') or '') == 'TavernMain'",
                "#int(Clara.var.get('tavern_visit_bar_1_seen', 0) or 0) == 1",
                "#int(Clara.var.get('tavern_visit_bar_2_seen', 0) or 0) == 0",
                "#int(Melissa.var.get('drawings_booklet_read', 0) or 0) == 1 or int(Melissa.var.get('drawings_booklet_left', 0) or 0) == 1",
                "#not household_runtime_event_seen_today('clara_tavern_visit')",
            ],
            None,
            "TavernMain",
            "clara_tavern_visit",
            2,
        ),
        (
            "story_clara_melissa_room_visit_0",
            None, (16, 22), None,
            1,
            None,
            [
                "#960 <= int(clock_minutes or 0) <= 1379",
                "#str(getLocation('clara') or '') == 'TavernMelissaRoom'",
                "#str(getLocation('melissa') or '') == 'TavernMelissaRoom'",
                "#int(Melissa.var.get('bats_episode', 0) or 0) >= 8",
                "#int(Melissa.var.get('drawings_found', 0) or 0) == 1",
                "#int(Clara.var.get('melissa_room_visit_0_seen', 0) or 0) == 0",
                "#not household_runtime_event_seen_today('clara_melissa_room_visit')",
            ],
            None,
            "TavernMelissaRoom",
            "clara_room_visit",
            3,
        ),
        (
            "story_clara_melissa_room_visit_1",
            None, (16, 22), None,
            1,
            None,
            [
                "#960 <= int(clock_minutes or 0) <= 1379",
                "#str(getLocation('clara') or '') == 'TavernMelissaRoom'",
                "#str(getLocation('melissa') or '') == 'TavernMelissaRoom'",
                "#int(Melissa.var.get('bats_episode', 0) or 0) >= 8",
                "#int(Clara.var.get('melissa_room_visit_0_seen', 0) or 0) == 1",
                "#int(Clara.var.get('melissa_room_visit_1_seen', 0) or 0) == 0",
                "#not household_runtime_event_seen_today('clara_melissa_room_visit')",
            ],
            None,
            "TavernMelissaRoom",
            "clara_room_visit",
            4,
        ),
        (
            "story_clara_melissa_room_visit_2",
            None, (16, 22), None,
            1,
            None,
            [
                "#960 <= int(clock_minutes or 0) <= 1379",
                "#str(getLocation('clara') or '') == 'TavernMelissaRoom'",
                "#str(getLocation('melissa') or '') == 'TavernMelissaRoom'",
                "#int(Melissa.var.get('bats_episode', 0) or 0) >= 8",
                "#int(Clara.var.get('melissa_room_visit_1_seen', 0) or 0) == 1",
                "#int(Clara.var.get('melissa_room_visit_2_seen', 0) or 0) == 0",
                "#not household_runtime_event_seen_today('clara_melissa_room_visit')",
            ],
            None,
            "TavernMelissaRoom",
            "clara_room_visit",
            5,
        ),
    ], highlight=False, threaded=True),
]
define beckyThreadList = []
define eddieThreadList = []
define irmaThreadList = []
define churchThreadList = []
define mongolThreadList = []
define cityGuardThreadList = []
define sherwoodThreadList = []
define tavernThreadList = [
    RThreadData(0, "tavern", "WorkRandomEvents", None, [1, [
        # (target, day, hour, delay, probability, reqs, condition, item, location, action, priority)
        (
            "TavernWorkEventTrigger", None, None, None,
            1,
            None,
            [
                "#tavern_work_planned_for('WaitressHarass', CurLoc, time)",
            ],
            None,
            "TavernMain",
            "tavern_work",
            200,
        ),
        (
            "TavernWorkEventTrigger", None, None, None,
            1,
            None,
            [
                "#tavern_work_planned_for('CleaningHarass', CurLoc, time)",
            ],
            None,
            "TavernMain",
            "tavern_work",
            210,
        ),
        (
            "TavernWorkEventTrigger", None, None, None,
            1,
            None,
            [
                "#tavern_work_planned_for('FightSmall', CurLoc, time)",
            ],
            None,
            "TavernMain",
            "tavern_work",
            220,
        ),
        (
            "TavernWorkEventTrigger", None, None, None,
            1,
            None,
            [
                "#tavern_work_planned_for('AmandaLizaTalk', CurLoc, time)",
            ],
            None,
            "TavernMain",
            "tavern_work",
            230,
        ),
    ]], highlight=False, threaded=False),
]
define cityThreadList = [
    RThreadData(0, "city", "StreetChronicles", None, [1, [
        # (target, day, hour, delay, probability, reqs, condition, item, location, action, priority)
        (
            "TownStreetPatrolEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetPatrolEvent')",
                "#int(GuardCaptainVar.get('street_pass', 0) or 0) == 0",
                "#town_street.patrol_allowed(CurLoc)",
            ],
            None,
            "StreetTavern",
            "enter",
            700,
        ),
        (
            "TownStreetThugsEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetThugsEvent')",
                "#int(TownStreetFightToday or 0) == 0",
                "#town_street.thug_allowed(CurLoc)",
            ],
            None,
            "StreetTavern",
            "enter",
            710,
        ),
        (
            "TownStreetHelpEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetHelpEvent')",
                "#town_street.help_allowed(CurLoc)",
            ],
            None,
            "StreetTavern",
            "enter",
            720,
        ),
        (
            "TownRandomChronicleEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownRandomChronicleEvent')",
            ],
            None,
            "StreetTavern",
            "enter",
            900,
        ),
        (
            "TownStreetPatrolEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetPatrolEvent')",
                "#int(GuardCaptainVar.get('street_pass', 0) or 0) == 0",
                "#town_street.patrol_allowed(CurLoc)",
            ],
            None,
            "MarketPlace",
            "enter",
            700,
        ),
        (
            "TownStreetThugsEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetThugsEvent')",
                "#int(TownStreetFightToday or 0) == 0",
                "#town_street.thug_allowed(CurLoc)",
            ],
            None,
            "MarketPlace",
            "enter",
            710,
        ),
        (
            "TownStreetHelpEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetHelpEvent')",
                "#town_street.help_allowed(CurLoc)",
            ],
            None,
            "MarketPlace",
            "enter",
            720,
        ),
        (
            "TownRandomChronicleEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownRandomChronicleEvent')",
            ],
            None,
            "MarketPlace",
            "enter",
            900,
        ),
        (
            "TownStreetPatrolEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetPatrolEvent')",
                "#int(GuardCaptainVar.get('street_pass', 0) or 0) == 0",
                "#town_street.patrol_allowed(CurLoc)",
            ],
            None,
            "PortStreets",
            "enter",
            700,
        ),
        (
            "TownStreetThugsEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetThugsEvent')",
                "#int(TownStreetFightToday or 0) == 0",
                "#town_street.thug_allowed(CurLoc)",
            ],
            None,
            "PortStreets",
            "enter",
            710,
        ),
        (
            "TownStreetHelpEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetHelpEvent')",
                "#town_street.help_allowed(CurLoc)",
            ],
            None,
            "PortStreets",
            "enter",
            720,
        ),
        (
            "TownRandomChronicleEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownRandomChronicleEvent')",
            ],
            None,
            "PortStreets",
            "enter",
            900,
        ),
        (
            "TownStreetPatrolEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetPatrolEvent')",
                "#int(GuardCaptainVar.get('street_pass', 0) or 0) == 0",
                "#town_street.patrol_allowed(CurLoc)",
            ],
            None,
            "ArtisansQuarter",
            "enter",
            700,
        ),
        (
            "TownStreetThugsEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetThugsEvent')",
                "#int(TownStreetFightToday or 0) == 0",
                "#town_street.thug_allowed(CurLoc)",
            ],
            None,
            "ArtisansQuarter",
            "enter",
            710,
        ),
        (
            "TownStreetHelpEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownStreetHelpEvent')",
                "#town_street.help_allowed(CurLoc)",
            ],
            None,
            "ArtisansQuarter",
            "enter",
            720,
        ),
        (
            "TownRandomChronicleEvent", None, None, None,
            1,
            None,
            [
                "#town_street.location_allowed(CurLoc)",
                "#int(TownStreetEventsToday or 0) < 2",
                "#not town_street.random_seen_this_slot(CurLoc)",
                "#town_street.planned_for(CurLoc, 'TownRandomChronicleEvent')",
            ],
            None,
            "ArtisansQuarter",
            "enter",
            900,
        ),
    ]], highlight=False, threaded=False),
]
define lizaThreadList = [
    LThreadData(0, "liza", "PortStreetClients", None, [
        (
            "story_liza_portstreet_clients",
            None, None, None,
            1,
            None,
            [
                "#Liza.portstreet_client_event_available()",
            ],
            None,
            "PortStreets",
            "street_clients_liza",
            100,
        ),
    ], highlight=False, threaded=False),
    LThreadData(0, "liza", "ChurchAfterSermon", None, [
        (
            "story_liza_church_after_sermon",
            7, (11, 12), None,
            1,
            None,
            [
                "#church_after_cermon_action_visible()",
                "#Liza.church_after_sermon_event_available()",
            ],
            None,
            "Church",
            "after_cermon_walk",
            120,
        ),
    ], highlight=False, threaded=False),
]
define georgettThreadList = [
    LThreadData(0, "georgett", "ChurchServiceBench", None, [
        (
            "story_georgett_church_service_bench",
            7, (8, 9), None,
            1,
            None,
            [
                "#church_service_action_visible()",
                "#bool(Georgett.known) or bool(knowsMC.get('georgett', False)) or people_to_int(Georgett.rel, 0) > 0",
                "#npc_schedule_georgett_church_visible()",
                "#people_to_int(Georgett.story_value('foundinchurch', 0), 0) > 0",
                "#people_to_int(cametoday, 0) < people_to_int(cancumdaily, 0)",
                "#people_to_int(Friends.get('georgett', Georgett.rel), 0) >= 6",
                "#people_to_int(Georgett.rel, 0) >= 6",
                "#people_to_int(sluttiness.get('georgett', Georgett.corruption), 0) >= 50",
                "#people_to_int(Georgett.corruption, 0) >= 50",
                "#people_to_int(HadSex.get('georgett', 0), 0) >= 3",
            ],
            None,
            "Church",
            "georgett_church_service_bench",
            100,
        ),
    ], highlight=False, threaded=False),
    LThreadData(0, "georgett", "ChurchServiceDoggy", None, [
        (
            "story_georgett_church_service_doggy",
            7, (8, 9), None,
            1,
            None,
            [
                "#church_service_action_visible()",
                "#bool(Georgett.known) or bool(knowsMC.get('georgett', False)) or people_to_int(Georgett.rel, 0) > 0",
                "#npc_schedule_georgett_church_visible()",
                "#people_to_int(Georgett.story_value('foundinchurch', 0), 0) > 0",
                "#people_to_int(cametoday, 0) < people_to_int(cancumdaily, 0)",
                "#people_to_int(Friends.get('georgett', Georgett.rel), 0) >= 6",
                "#people_to_int(Georgett.rel, 0) >= 6",
                "#people_to_int(sluttiness.get('georgett', Georgett.corruption), 0) >= 50",
                "#people_to_int(Georgett.corruption, 0) >= 50",
                "#people_to_int(HadSex.get('georgett', 0), 0) >= 3",
            ],
            None,
            "Church",
            "georgett_church_service_doggy",
            100,
        ),
    ], highlight=False, threaded=False),
    LThreadData(0, "georgett", "ChurchServiceWithLiza", None, [
        (
            "story_georgett_church_service_with_liza",
            7, (8, 9), None,
            1,
            None,
            [
                "#church_service_action_visible()",
                "#bool(Georgett.known) or bool(knowsMC.get('georgett', False)) or people_to_int(Georgett.rel, 0) > 0",
                "#npc_schedule_georgett_church_visible()",
                "#people_to_int(Georgett.story_value('foundinchurch', 0), 0) > 0",
                "#people_to_int(Georgett.story_value('askkids', 0), 0) > 0",
                "#people_to_int(Georgett.story_value('fuckinchurch', 0), 0) > 0",
                "#people_to_int(cametoday, 0) < people_to_int(cancumdaily, 0)",
                "#people_to_int(Friends.get('georgett', Georgett.rel), 0) >= 6",
                "#people_to_int(Georgett.rel, 0) >= 6",
                "#people_to_int(sluttiness.get('georgett', Georgett.corruption), 0) >= 50",
                "#people_to_int(Georgett.corruption, 0) >= 50",
                "#people_to_int(HadSex.get('georgett', 0), 0) >= 3",
            ],
            None,
            "Church",
            "georgett_church_service_with_liza",
            100,
        ),
    ], highlight=False, threaded=False),
    LThreadData(0, "georgett", "PortStreetClients", None, [
        (
            "story_georgett_portstreet_clients",
            None, None, None,
            1,
            None,
            [
                "#Georgett.portstreet_client_event_available()",
            ],
            None,
            "PortStreets",
            "street_clients_georgett",
            100,
        ),
    ], highlight=False, threaded=False),
    LThreadData(0, "georgett", "ChurchAfterSermon", None, [
        (
            "story_georgett_church_after_sermon",
            7, (11, 12), None,
            1,
            None,
            [
                "#church_after_cermon_action_visible()",
                "#Georgett.church_after_sermon_event_available()",
            ],
            None,
            "Church",
            "after_cermon_walk",
            110,
        ),
    ], highlight=False, threaded=False),
]

define threadListsByGirl = {
    "amanda": amandaThreadList,
    "melissa": melissaThreadList,
    "sandra": sandraThreadList,
    "clara": claraThreadList,
    "mongol": mongolThreadList,
    "cityguard": cityGuardThreadList,
    "sherwood": sherwoodThreadList,
    "becky": beckyThreadList,
    "eddie": eddieThreadList,
    "irma": irmaThreadList,
    "church": churchThreadList,
    "liza": lizaThreadList,
    "georgett": georgettThreadList,
    "tavern": tavernThreadList,
    "city": cityThreadList,
}

define threadList = (
    amandaThreadList
    + melissaThreadList
    + sandraThreadList
    + claraThreadList
    + mongolThreadList
    + cityGuardThreadList
    + sherwoodThreadList
    + beckyThreadList
    + eddieThreadList
    + irmaThreadList
    + churchThreadList
    + lizaThreadList
    + georgettThreadList
    + tavernThreadList
    + cityThreadList
)

define threadData = loadThreadData(threadList)
default threads = createThreads()

